name: Build and Upload Artifacts

on:
    push:
        branches:
            - main
            - master
        paths-ignore:
            - "docs/**"
            - "**/*.md"
            - "appveyor.xml"
            - ".travis.yml"
            - ".travis/**"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        name: "Build with JDK 17"
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true
            ACTIONS_RUNNER_DEBUG: true
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 50

            - name: "Set up JDK 21 and 17"
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  # Install both Java versions - 21 for build-logic, 17 for main build
                  java-version: |
                      17
                      21

            - name: "Validate Gradle wrapper"
              uses: gradle/wrapper-validation-action@v2
              continue-on-error: true
              timeout-minutes: 3

            - uses: burrunan/gradle-cache-action@v2
              name: Build project
              env:
                  S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
                  S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
              with:
                  read-only: ${{ github.repository != 'pgjdbc/pgjdbc' || secrets.S3_BUILD_CACHE_ACCESS_KEY_ID == '' }}
                  job-id: build-jdk17
                  arguments: --no-daemon clean assemble jandex osgiJar publishToMavenLocal -Pgh -PskipJavadoc=true
                  properties: |
                      skipSnapshot=true
                      jdkBuildVersion=17
                      jdkTestVersion=17
                      # We provision JDKs with GitHub Actions for caching purposes, so Gradle should rather fail in case JDK is not found
                      org.gradle.java.installations.auto-download=false

            - name: "Build source distribution"
              uses: burrunan/gradle-cache-action@v2
              env:
                  S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
                  S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
              with:
                  read-only: ${{ github.repository != 'pgjdbc/pgjdbc' || secrets.S3_BUILD_CACHE_ACCESS_KEY_ID == '' }}
                  job-id: build-jdk17-src
                  arguments: --no-daemon sourceDistribution
                  properties: |
                      skipSnapshot=true

            - name: Upload JAR artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: pgjdbc-jars-build-${{ github.run_number }}
                  path: |
                      pgjdbc/build/libs/*.jar
                      pgjdbc/build/libs/*.pom
                  retention-days: 30

            - name: Upload Maven Local artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: pgjdbc-maven-local-${{ github.run_number }}
                  path: |
                      ~/.m2/repository/org/postgresql/postgresql/**/*.jar
                      ~/.m2/repository/org/postgresql/postgresql/**/*.pom
                  retention-days: 30

            - name: Upload source distribution
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: pgjdbc-source-dist-${{ github.run_number }}
                  path: |
                      pgjdbc/build/distributions/*.tar.gz
                      pgjdbc/build/distributions/*.zip
                  retention-days: 30
